### ISSUE TITLE
CA cert

### ISSUE THREAD

**Issue by Dimitrievich** [marcelloc/Unofficial-pfSense-packages#120]
Today chrome or another brouthers have one problem 
NET::ERR_CERT_DATE_INVALID
How to resolve this?

**Comment by kontrol-br** [comment]
Hello Dimitri
You need to change the file:  \usr\local\pkg\e2guardian.conf.template 

find the lines below with "generatedcertstart = " and change it accordingly (Unix time) 

#Generated cert end time (in unix time) - optional
# defaults to generatedcertstart + 10 years
#genratedcertend =
generatedcertstart = 1733363579   #Dec 05 2024 01:52:59

then SAVE a new config to overwrite the e2guardian.conf  file.
Clear the MITM cache and recycle the e2g service.

That will fix it.  ;-)
