### ISSUE TITLE
Use INFO instead of WARN for Subject logging

### ISSUE THREAD

**Issue by spec1re** [marcelloc/Unofficial-pfSense-packages#2]
```
# Log Subject Lines in Postfix
/^Subject:/ INFO 
```
It's a less intrusive and gives better results for tail/postfix-logwatch/pflogsumm, since its not a real warning.

Files need to be edit: postfix.php, postfix_search.php and in postfix.xml (just the description hint)

**Comment by marcelloc** [comment]
Thanks for the suggestion. I'll change it soon

**Comment by marcelloc** [comment]
Fixed.
Thanks again.
https://github.com/marcelloc/Unofficial-pfSense-packages/commit/d934d0cef8df9aaa39a8a49bc890b2cd5240f988
