### ISSUE TITLE
Get erro when installation try fetch file from repo

### ISSUE THREAD

**Issue by aderbas** [marcelloc/Unofficial-pfSense-packages#20]
When I try to install it gives error. This file not found: https://github.com/marcelloc/Unofficial-pfSense-packages/raw/master/repo-i386/pfSense-pkg-WPAD-0.3.0.2.txz

**Comment by marcelloc** [comment]
fetch from this link if still on 2.3 32 bits 

https://github.com/marcelloc/Unofficial-pfSense-packages/blob/master/repo-i386/pfSense-pkg-WPAD-0.3.0.1.txz
