### ISSUE TITLE
E2Guardian v5 and the GUI

### ISSUE THREAD

**Issue by robotman3000** [marcelloc/Unofficial-pfSense-packages#28]
Hi, I am wondering what plans there are, if any, to update the GUI for e2guardian to support the changes and new features being brought by v5?

**Comment by marcelloc** [comment]
I'll start taking a look at v5. hope this compiles and run smooth on freebsd/pfSense.
It will need a lot of work on gui as its not backward compatible with v4 configuration files

**Comment by robotman3000** [comment]
Yes indeed. That's actually why I hadn't done it yet myself. I've had issues getting v5 e2g to run on pfsense. I know I reported a few issues that have been fixed now but I haven't had time to work on this in a while.
