### ISSUE TITLE
smtpd_helo_restrictions is to restrictive

### ISSUE THREAD

**Issue by spec1re** [marcelloc/Unofficial-pfSense-packages#3]
It gives to many FP, instead just log **reject_invalid_helo_hostname**, **reject_invalid_helo_hostname** and check if it has a valid reverse name.

```
smtpd_helo_restrictions = check_helo_access pcre:{$pf_dir}/etc/postfix/helo_check,
				warn_if_reject reject_invalid_helo_hostname,
				warn_if_reject reject_unknown_client_hostname,
				reject_unknown_reverse_client_hostname,
				reject_non_fqdn_helo_hostname,
				permit
EOF;
```

People just turn off HELO checks because of this.

**Comment by marcelloc** [comment]
I'll put it as a GUI option. Thanks again

**Comment by marcelloc** [comment]
updated. Thanks again.
https://github.com/marcelloc/Unofficial-pfSense-packages/commit/5891bc1692c8346b8147fd3c6b0bbcab99ba943c
