### ISSUE TITLE
Unable to update

### ISSUE THREAD

**Issue by uhlhosting** [marcelloc/Unofficial-pfSense-packages#37]
Updating Unofficial repository catalogue...
pkg-static: Repository Unofficial load error: access repo file(/var/db/pkg/repo-Unofficial.sqlite) failed: No such file or directory
pkg-static: https://github.com/marcelloc/Unofficial-pfSense-packages/raw/master/repo-24/meta.txz: Not Found
repository Unofficial has no meta file, using default settings
pkg-static: https://github.com/marcelloc/Unofficial-pfSense-packages/raw/master/repo-24/packagesite.txz: Not Found
Unable to update repository Unofficial

**Comment by marcelloc** [comment]
Update the repository file again, I've changed the repo structure and seems that the symlink to aold dir structure didn't work.

fetch -q -o /usr/local/etc/pkg/repos/Unofficial.conf https://raw.githubusercontent.com/marcelloc/Unofficial-pfSense-packages/master/Unofficial.conf

**Comment by marcelloc** [comment]
I did one last move, so you may need to update repository file again.

**Comment by uhlhosting** [comment]
its fixed now
