### ISSUE TITLE
E2Guardian - Denied log not showing HTTPS sites

### ISSUE THREAD

**Issue by forid786** [marcelloc/Unofficial-pfSense-packages#38]
Hi,

When a user browses to a restricted HTTPS site. It doesn't appear on the "Detailed denied log", where as it does appear on the access table, therefore the proxy definitely detects the URL and blocks it.

Could you have a look into this when possible please?

**Comment by marcelloc** [comment]
Can you check if it's on /var/log/e2guardian/denied.log but not on real time tab?

**Comment by forid786** [comment]
Issue resolved since way back! Closing issue.
