### ISSUE TITLE
Trying to install on SG-3100

### ISSUE THREAD

**Issue by epick** [marcelloc/Unofficial-pfSense-packages#39]
Hi,

I tried to get e2guardian but I get this error:
 [2.4.3-RELEASE][admin@local.lan]/: pkg update
Updating Unofficial repository catalogue...
pkg: Repository Unofficial load error: access repo file(/var/db/pkg/repo-Unofficial.sqlite) failed: No such file or directory
pkg: https://github.com/marcelloc/Unofficial-pfSense-packages/raw/master/repo/FreeBSD:11:armv6/meta.txz: Not Found
repository Unofficial has no meta file, using default settings
pkg: https://github.com/marcelloc/Unofficial-pfSense-packages/raw/master/repo/FreeBSD:11:armv6/packagesite.txz: Not Found

Thanks

**Comment by marcelloc** [comment]
I have no armv6 device to compile these packages, sorry.

**Comment by epick** [comment]
Hi, thanks for reply. You have any plan to build a package for this
arquitectura?.

**Comment by marcelloc** [comment]
https://wiki.freebsd.org/QemuUserModeHowTo

If this is enough to build a compatible amrv6 environment to compile pfSense packages, then
