### ISSUE TITLE
Unable to set time limiting syntax on ACLs

### ISSUE THREAD

**Issue by chinaina** [marcelloc/Unofficial-pfSense-packages#41]
I was not able to enable the time limitation on my ACLs.
I didn't  find any tip on internet but a I solved my problem, changing this line:

https://github.com/marcelloc/Unofficial-pfSense-packages/blob/9038df836abc95760de7e9bc74e099d0a624b959/pkg-e2guardian5/files/usr/local/pkg/e2guardian.inc#L1350

to:
```
	//remove comments and blank lines
                $save_array = array_unique(preg_grep("/^(\w|\"|\'|\/|\.|\<|\(|\*|\^|\# acl |\#time|\#listcategory|\#noconvert|\#ENDLIST)/", ${$list_value}));
```
I'm reporting my issue here for correction and documentation.

**Comment by marcelloc** [comment]
Use time schedules form pfSense and apply it on first field of each acl.

**Comment by chinaina** [comment]
I didn't see this option during the configuration.
Is much easier than the _time_ _syntax_.

Thanks Marcelo!
