### ISSUE TITLE
Apply patch

### ISSUE THREAD

**Issue by delumerlino** [marcelloc/Unofficial-pfSense-packages#47]
Hi,
how to apply patch?
I have copied the patch url, fetched and applied but I cannot see any package...

Thanks a lot

**Comment by cindymanu** [comment]
Olá, também tive problemas ao aplicar o patch. 
Faço isso, seguindo o manual:
![image](https://user-images.githubusercontent.com/45361054/49018339-50440180-f172-11e8-8c8a-54227eb0d192.png)

O erro aparece assim
![image](https://user-images.githubusercontent.com/45361054/49018291-2db1e880-f172-11e8-85a1-693f169989c0.png)

e depois

![image](https://user-images.githubusercontent.com/45361054/49018307-360a2380-f172-11e8-9f03-edfafe453b29.png)

Desde já, agradeço.

**Comment by 2w-consultoria** [comment]
Tente fazer da seguinte forma:
Description: 
Unofficial-pfSense-packages

URL/Commit ID: 	
https://raw.githubusercontent.com/marcelloc/Unofficial-pfSense-packages/master/244_unofficial_packages_list.patch

Path Strip Count: 1

Auto Apply: Y

-> Fetch, Apply

**Comment by cindymanu** [comment]
Mesmo colocando, como na imagem abaixo, o código vai automaticamente no Patch Content, ainda dá um erro:
![image](https://user-images.githubusercontent.com/45361054/49024280-47f2c300-f180-11e8-9e06-7eafe78aa814.png)

O erro:
![image](https://user-images.githubusercontent.com/45361054/49024311-5a6cfc80-f180-11e8-9568-82b741dff18c.png)

Desde já, agradeço.

**Comment by 2w-consultoria** [comment]
Arqui funciona normal em vários clientes da forma que te passei.

**Comment by marcelloc** [comment]
https://www.youtube.com/watch?v=NuhxsyatYAs
