### ISSUE TITLE
Problem installing postfix pkg-static

### ISSUE THREAD

**Issue by rrafael01** [marcelloc/Unofficial-pfSense-packages#59]
I want to add postifix in my pfsense 2.4.4 when it tries to download following error:

pkg-static: https://github.com/marcelloc/Unofficial-pfSense-packages/raw/master/repo/FreeBSD:11:amd64/pfSense-pkg-postfix-3.3.4_2.txz: Not Found

When I access github.com/marcelloc .. I see that the package has changed to pfSense-pkg-postfix-3.3.4_3.txz can anyone help me?

**Comment by marcelloc** [comment]
Sure, I'll fix it today. Im still fixing things to get it working on 2.4.4

**Comment by marcelloc** [comment]
Postfix package should be installing fine now. Take a look.

**Comment by rrafael01** [comment]
Worked perfectly thanks.
