### ISSUE TITLE
pkg-filer - PHP ERROR: Type: 64,

### ISSUE THREAD

**Issue by tomaswaldow** [marcelloc/Unofficial-pfSense-packages#6]
Olá Marcello.
Ao instalar o pacote filer ocorreu o erro em anexo, obrigado.

![image](https://cloud.githubusercontent.com/assets/151730/26492306/be375866-41e9-11e7-88e7-3ca5fa5f5aaa.png)

**Comment by marcelloc** [comment]
Tinha uma chamada de arquivo de outro pacote.

Acabei de arrumar. Baixa e executa o instalador novamente e me avisa se deu tudo certo

**Comment by tomaswaldow** [comment]
Obrigado, deu certo.
