### ISSUE TITLE
E2Guardian Package - LDAP users search - Crontab entry. (suggestion)

### ISSUE THREAD

**Issue by Kontrol-BR** [marcelloc/Unofficial-pfSense-packages#63]
Hello Marcello,
Greetings.
I am testing the E2Guardian package I see there is an issue with the LDAP Groups search, Update Frequency.
The package is creating a crontab entry with an issue. It is adding a "0" (zero) instead of * (asterisk).
I have changed the line 1595 from:

`e2g_check_cron("{$cron_cmd} $e2_group_source '{$e2guardian_groups[$e2_group_source]}'", "create", "*/{$matches[1]}", "0");`

to:
`e2g_check_cron("{$cron_cmd} $e2_group_source '{$e2guardian_groups[$e2_group_source]}'", "create", "*/{$matches[1]}", "*");`

and Line 1598 from:

`e2g_check_cron("{$cron_cmd} $e2_group_source '{$e2guardian_groups[$e2_group_source]}'", "create",  "0", "*/{$matches[1]}");`

to:

`e2g_check_cron("{$cron_cmd} $e2_group_source '{$e2guardian_groups[$e2_group_source]}'", "create",  "*", "*/{$matches[1]}");`

It seems it fixed the issue. 
Anyway, Just wanted to let you know.

Best regards,

Fabricio.

**Comment by forid786** [comment]
Hi Fabricio,

Nice one spotting that! Feel free to send a pull request :)

**Comment by Kontrol-BR** [comment]
Hi Forid,
Will do as soon as I finish the tests. There are some things I have to confirm before it.
for the H (hour) the "0"(zero)  is fine, but not for M (minute), so I am testing it.

Thanks,
Fabricio.

**Comment by marcelloc** [comment]
Kontrol-BR, the 0 on line 1595 was an issue but on hour cron(line 1598) it needs to be a number to prevent ldap fetch from being executed every minute on hour cron match.

**Comment by marcelloc** [comment]
https://github.com/marcelloc/Unofficial-pfSense-packages/commit/f5e1b31e59a8e55df70228064f498f86e9778e7b
