### ISSUE TITLE
E2Guardian Stuck at Reinstallation

### ISSUE THREAD

**Issue by rmundel** [marcelloc/Unofficial-pfSense-packages#64]
Hi folks.
Tryed to reinstall E2Guardian package in the Web UI and it is stuck at:

Executing custom_php_install_command()...Checking E2guardian Blacklists... One moment please...

Uninstallation get stuck too.

Any thoughs?

**Comment by forid786** [comment]
Go onto SSH - and do a pkg remove e2guardian and then try it again. I've had this happen in the past before, it's usually when it can't fetch the blacklist for one reason or another.

**Comment by rmundel** [comment]
Actually solved rebooting. Thanks
