### ISSUE TITLE
Mailscanner

### ISSUE THREAD

**Issue by tomaswaldow** [marcelloc/Unofficial-pfSense-packages#7]
Olá Marcello, desculpe chamar por aqui, não achei outro local no Github para te enviar uma mensagem,
Quero testar e ajudar a manter o projeto, hoje uso o Scrollout F1, mas pouco conhecimento sobre Mailscanner . Quero saber se você tem algum material de estudo ou guia para a configuração inicial. Obrigado.

**Comment by marcelloc** [comment]
Da uma olhada na documentação do projeto. O Mailscanner é bem completo. Faz uma infinidade de testes além de integrar com o spamassassin

https://s3.amazonaws.com/msv5/docs/ms-admin-guide.pdf
https://www.mailscanner.info/MailScanner.conf.index.html

No sys-squad.com tem uma aula só sobre o antispam. A ferramenta evoluiu bastante da aula que tem lá pra cá, mas como sei que é aluno dos cursos, acredito que tenha acesso ao vídeo.

**Comment by tomaswaldow** [comment]
Certo, como uso o Scrollout, estou pensando em usar o Postfix mesmo e fazer o filtro por lá, Obrigado.

**Comment by tomaswaldow** [comment]
Obrigado,
