### ISSUE TITLE
Pacote UserAuth não disponivel para versão 2.4.5

### ISSUE THREAD

**Issue by rgerald** [marcelloc/Unofficial-pfSense-packages#77]
Olá, recentemente instalei um Pfsense e preciso configurar a autenticação com o AD, porem não consegui achar o paco de UserAuth  nessa versão.

**Comment by 2w-consultoria** [comment]
Userauth tem que adquiir licença: https://conexti.com.br/userauth/
--
Tomas Waldow


Em dom., 17 de mai. de 2020 às 12:51, rgeraldin <notifications@github.com>
escreveu:

**Comment by marcelloc** [comment]
@rgerald, o pacote é gratuito até 8 conexões, siga o procedimento de configuração do repositório no link que o @2w-consultoria postou.
