### ISSUE TITLE
Sugestão: Privilegios de usuarios

### ISSUE THREAD

**Issue by skycrash** [marcelloc/Unofficial-pfSense-packages#78]
Hoje não possui na pagina de Gerenciamento de Usuarios, como dar privilegio para algum usuario acessar somente essas configuracoes do e2guardian. 
Sabe como posso adicionar manualmente para nao precisar liberar todos os itens do pfsense ? 
![image](https://user-images.githubusercontent.com/20068263/91189045-57da6680-e6c8-11ea-8e1d-fdd3a170fb8d.png)

**Comment by marcelloc** [comment]
A permissão existe sim.  

WebCfg -Services: E2guardian package

https://github.com/marcelloc/Unofficial-pfSense-packages/blob/master/pkg-e2guardian5/files/etc/inc/priv/e2guardian.priv.inc

**Comment by skycrash** [comment]
Deu certo, não estava aparecendo no Menu, acredito que eu estava comendo alguma outra permissão.
Desculpe e obrigado ;-)
