### ISSUE TITLE
Postfix : warning: not owned by postfix

### ISSUE THREAD

**Issue by tomaswaldow** [marcelloc/Unofficial-pfSense-packages#8]
Boa tarde, começando os testes com o Posftfix, e encontrei o seguinte erro:

![image](https://cloud.githubusercontent.com/assets/151730/26504725/20bf13c0-421c-11e7-89bd-f66f96757231.png)

Rodei manualmente: chown -R postfix:postfix /var/db/postfix/ e parece que resolveu, consegui receber um e-mail. Não estava sendo criado o arquivo de dados sqlite.

**Comment by marcelloc** [comment]
Não precisa se preocupar com esses avisos para os arquivos .db, os arquivos de dados não são consultados pelo daemon do postfix. Estas são as bases de dados que a interface web consulta na pesquisa.

**Comment by tomaswaldow** [comment]
Certo, mas fica melhor para eu fazer consultas, obrigado.
