### ISSUE TITLE
Arquivo mk.244.tar.gz PFSENSE 2.4.5

### ISSUE THREAD

**Issue by mauriciorm** [marcelloc/Unofficial-pfSense-packages#80]
Caro,

Ao executar o script dos pacotes do cpan para o mailscanner no pFsense 2.4.5 os arquivos não funcionam. Vocês já tem um novo pacote para a versão 2.4.5 ?

**Comment by marcelloc** [comment]
Na 2.4.5 tem alguns binários "capados"  do FreeBSD. Ainda não tive tempo de refazer esse pacote pra 2.4.5

**Comment by mauriciorm** [comment]
Eu verifiquei que está faltando os pacotes que podem ser encontrador no gcc8, instalei ele consegui compilar todos os arquivos.

**Comment by marcelloc** [comment]
Sim, muito bem lembrado. Tinha incluido o gcc8 no repositorio exatamente para compilar os pacotes. Já atualizei a documentação de instalação.
Obrigado pelos testes e lembremte
