### ISSUE TITLE
Cert errors after 2.5 update

### ISSUE THREAD

**Issue by forid786** [marcelloc/Unofficial-pfSense-packages#82]
When trying to install packages from the Unofficial repository after the 2.5 update, I am getting the following certificate errors:

`>>> Installing pfSense-pkg-E2guardian5... 
Updating Unofficial repository catalogue...
Certificate verification failed for /C=US/ST=California/L=San Francisco/O=GitHub, Inc./CN=www.github.com
34369257472:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:/usr/local/poudriere/jails/pfSense_v2_5_0_amd64/usr/src/crypto/openssl/ssl/statem/statem_clnt.c:1915:
Certificate verification failed for /C=US/ST=California/L=San Francisco/O=GitHub, Inc./CN=www.github.com
34369257472:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:/usr/local/poudriere/jails/pfSense_v2_5_0_amd64/usr/src/crypto/openssl/ssl/statem/statem_clnt.c:1915:
Certificate verification failed for /C=US/ST=California/L=San Francisco/O=GitHub, Inc./CN=www.github.com
34369257472:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:/usr/local/poudriere/jails/pfSense_v2_5_0_amd64/usr/src/crypto/openssl/ssl/statem/statem_clnt.c:1915:
Certificate verification failed for /C=US/ST=California/L=San Francisco/O=GitHub, Inc./CN=www.github.com`

Looks like pfSense no longer is trusting the Github certificate? I haven't had a chance to investigate further but has anyone else come across these problems?

**Comment by marcelloc** [comment]
I've just updated code and binaries for 2.5 .

I'll configure a vm to test this and see how to workaround?

**Comment by forid786** [comment]
Brilliant, thanks again for your hard work! @marcelloc

**Comment by thomascouto** [comment]
> When trying to install packages from the Unofficial repository after the 2.5 update, I am getting the following certificate errors:
> 
> `>>> Installing pfSense-pkg-E2guardian5... Updating Unofficial repository catalogue... Certificate verification failed for /C=US/ST=California/L=San Francisco/O=GitHub, Inc./CN=www.github.com 34369257472:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:/usr/local/poudriere/jails/pfSense_v2_5_0_amd64/usr/src/crypto/openssl/ssl/statem/statem_clnt.c:1915: Certificate verification failed for /C=US/ST=California/L=San Francisco/O=GitHub, Inc./CN=www.github.com 34369257472:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:/usr/local/poudriere/jails/pfSense_v2_5_0_amd64/usr/src/crypto/openssl/ssl/statem/statem_clnt.c:1915: Certificate verification failed for /C=US/ST=California/L=San Francisco/O=GitHub, Inc./CN=www.github.com 34369257472:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:/usr/local/poudriere/jails/pfSense_v2_5_0_amd64/usr/src/crypto/openssl/ssl/statem/statem_clnt.c:1915: Certificate verification failed for /C=US/ST=California/L=San Francisco/O=GitHub, Inc./CN=www.github.com`
> 
> Looks like pfSense no longer is trusting the Github certificate? I haven't had a chance to investigate further but has anyone else come across these problems?

Same here, since yesterday.

**Comment by forid786** [comment]
> > When trying to install packages from the Unofficial repository after the 2.5 update, I am getting the following certificate errors:
> > `>>> Installing pfSense-pkg-E2guardian5... Updating Unofficial repository catalogue... Certificate verification failed for /C=US/ST=California/L=San Francisco/O=GitHub, Inc./CN=www.github.com 34369257472:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:/usr/local/poudriere/jails/pfSense_v2_5_0_amd64/usr/src/crypto/openssl/ssl/statem/statem_clnt.c:1915: Certificate verification failed for /C=US/ST=California/L=San Francisco/O=GitHub, Inc./CN=www.github.com 34369257472:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:/usr/local/poudriere/jails/pfSense_v2_5_0_amd64/usr/src/crypto/openssl/ssl/statem/statem_clnt.c:1915: Certificate verification failed for /C=US/ST=California/L=San Francisco/O=GitHub, Inc./CN=www.github.com 34369257472:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:/usr/local/poudriere/jails/pfSense_v2_5_0_amd64/usr/src/crypto/openssl/ssl/statem/statem_clnt.c:1915: Certificate verification failed for /C=US/ST=California/L=San Francisco/O=GitHub, Inc./CN=www.github.com`
> > Looks like pfSense no longer is trusting the Github certificate? I haven't had a chance to investigate further but has anyone else come across these problems?
> 
> Same here, since yesterday.

@marcelloc Is looking into it already, it's possible Netgate are doing some cert pinning.

Another thing I realised, I couldn't upgrade from 2.4.5-P1 to 2.5.0 without removing the unofficial repo. I was seeing similar errors for pfsense base packages, after removing the unofficial repo I was able to upgrade just fine.

**Comment by thomascouto** [comment]
This issue started after I tried to install freeradius3 packaged from official repository. I removed @marcelloc repo and now i'm able to see available packages list, but i'm unable to install any package. 

note: 2.4.5-RELEASE (amd64)

**Comment by marcelloc** [comment]
Install process on 2.5 uses pkg-static with ssl/cert/fingerprint validation instead of traditional pkg.
I've copied repo files to a standar http server, try this url to install repo:

fetch -q -o /usr/local/etc/pkg/repos/Unofficial.conf https://raw.githubusercontent.com/marcelloc/Unofficial-pfSense-packages/master/Unofficial_no_ssl.conf

**Comment by RobertoMarcelino** [comment]
Agora sim!

**Comment by thomascouto** [comment]
Package list is showing now. Thanks!
Keep trying to understand why my package installer still dead...

**Comment by forid786** [comment]
Confirmed working, I have been able to see the package list and install packages without a hitch now. Thanks again for fixing this so fast @marcelloc much appreciated!

**Comment by RobertoMarcelino** [comment]
I did a new installation of pfSense 2.5.

I installed System_Patches and didn't add a patch.

I ran the command:
fetch -q -o /usr/local/etc/pkg/repos/Unofficial.conf https://raw.githubusercontent.com/marcelloc/Unofficial-pfSense-packages/master/Unofficial_no_ssl.conf

I created a patch and applied the link: https://raw.githubusercontent.com/marcelloc/Unofficial-pfSense-packages/master/pfSense_2.5_unofficial_packages_list.patch

In the list of packages, the SourceGuardian does not appear.

It is necessary for several processes, such as Sarg.

Is there a way to install SourceGuardian separately or will this problem be fixed?

**Comment by marcelloc** [comment]
> I did a new installation of pfSense 2.5.
> 
> I installed System_Patches and didn't add a patch.
> 
> I ran the command:
> fetch -q -o /usr/local/etc/pkg/repos/Unofficial.conf https://raw.githubusercontent.com/marcelloc/Unofficial-pfSense-packages/master/Unofficial_no_ssl.conf
> 
> I created a patch and applied the link: https://raw.githubusercontent.com/marcelloc/Unofficial-pfSense-packages/master/pfSense_2.5_unofficial_packages_list.patch
> 
> In the list of packages, the SourceGuardian does not appear.
> 
> It is necessary for several processes, such as Sarg.
> 
> Is there a way to install SourceGuardian separately or will this problem be fixed?

sourceguardian is on userauth/conexti repo, take a look here
https://www.conexti.com.br/userauth-e-ngrules-atualizados-para-o-pfsense-2-5/

**Comment by forid786** [comment]
Will mark this as closed as the workaround so far seems to be working (and working well). May need to be re-visited in the future if SSL support is to be added.
