### ISSUE TITLE
Erro mensagem PFsense: E2guardianBlacklist applied, check site and URL access lists for categories

### ISSUE THREAD

**Issue by rgnldo** [marcelloc/Unofficial-pfSense-packages#84]
E2Guardian instalado com sucesso e já em uso há algum tempo. Nas mensagens do PFSense, consta a mensagem **E2guardianBlacklist applied, check site and URL access lists for categories**. Há algum problema com os downloads programados da blacklist?

**Comment by marcelloc** [comment]
@rgnldo, esta é uma mensagem de sucesso, não de erro.
E2guardianBlacklist aplicadas, verifique nas acls de site e url as categorias atualizadas.
