### ISSUE TITLE
Cenário com o PF firewall operando com portas de acesso customizadas. 

### ISSUE THREAD

**Issue by rgnldo** [marcelloc/Unofficial-pfSense-packages#85]
Com o PFSense, nas regras de firewall LAN, configuro as portas de acesso por demanda (53,443 etc). Como configuro o e2guardian no modo transparente e SSL?

**Comment by marcelloc** [comment]
Veja se este vídeo te ajuda.
https://www.youtube.com/watch?v=tao1tiXFefk

**Comment by rgnldo** [comment]
Agradeço o retorno. Este seu vídeo é bem clássico quanto à instalação e configuração do E2guardian. Havia visualizado. Porém, não trata especificamente do firewall.
Organizei assim:
![image](https://user-images.githubusercontent.com/58551674/110244425-6211d300-7f3d-11eb-88e2-d12e88b75871.png)
Por favor, veja se concorda.
