### ISSUE TITLE
Mailscanner error

### ISSUE THREAD

**Issue by bhillcv** [marcelloc/Unofficial-pfSense-packages#93]
Olá.

Após a instalação do mailscanner no pfSense 2,5x o erro abaixo é reportado.

FreeBSD 12.2-STABLE 1b709158e581(RELENG_2_5_0) pfSense

Crash report details:

PHP Errors:
[05-Jul-2021 15:41:26 America/Sao_Paulo] PHP Fatal error:  Uncaught Error: Class 'ZipArchive' not found in /usr/local/pkg/mailscanner.inc:862
Stack trace:
#0 /usr/local/pkg/mailscanner.inc(903): get_github_plugin('https://github....', '', '/usr/local/bin/...')
#1 /etc/inc/pkg-utils.inc(801) : eval()'d code(1): mailscanner_php_install_command()
#2 /etc/inc/pkg-utils.inc(801): eval()
#3 /etc/inc/pkg-utils.inc(922): eval_once('mailscanner_php...')
#4 /etc/rc.packages(76): install_package_xml('mailscanner')
#5 {main}
  thrown in /usr/local/pkg/mailscanner.inc on line 862

No FreeBSD crash data found.

Alguém já pegou este erro no pfsense?

**Comment by marcelloc** [comment]
veja se estes dois pacotes estão instalados no seu pfsense

p5-Archive-Zip-1.68.txz
php74-zip-7.4.15.txz

**Comment by bhillcv** [comment]
Olá Marcelo.

Faltava o p5-Archive. Muito obrigado.



Em seg., 5 de jul. de 2021 às 17:45, Marcello Coutinho <
***@***.***> escreveu:

**Comment by bhillcv** [comment]
Olá Marcelo.

Faltava o p5-Archive. Muito obrigado.
