### ISSUE TITLE
2.5.2-RELEASE 25_unofficial_packages_list.patch has issues

### ISSUE THREAD

**Issue by ageekhere** [marcelloc/Unofficial-pfSense-packages#94]
/usr/bin/patch --directory=/ -t -p1 -i /var/patches/606ac5330f6b3.patch --check --forward --ignore-whitespace

Hmm...  Looks like a unified diff to me...
The text leading up to this was:
--------------------------
|--- /etc/inc/pkg-utils.orig.inc 2021-02-18 11:18:07.356449000 -0300
|+++ /etc/inc/pkg-utils.inc      2021-02-18 15:26:41.486078000 -0300
--------------------------
Patching file etc/inc/pkg-utils.inc using Plan A...
Hunk #1 succeeded at 403 (offset 1 line).
Hunk #2 succeeded at 500 (offset 1 line).
done

**Comment by forid786** [comment]
Hey there,

Is this happening on a fresh install of pfSense 2.5.2? I can't see any changes in 2.5.2 that should really cause a problem. I've previously had the unnoficial repo installed, upgraded to 2.5.2 and can still access Unofficial packages just fine.

**Comment by ageekhere** [comment]
Hi, was on a fresh install of pfSense 2.5.0 then just updated to 2.5.2. When i go to System\Patches and run the Test on the script i get 
Patch can be applied cleanly (detail)
Patch can NOT be reverted cleanly (detail)
with the above error

**Comment by ageekhere** [comment]
I checked and Unofficial.conf is in /usr/local/etc/pkg/repos
https://forums.freebsd.org/threads/problem-with-patching-hmm-looks-like-a-unified-diff-to-me.42044/
Maybe "It means that patch(1) can't find the file it is supposed to patch"

**Comment by marcelloc** [comment]
This is the important info:

> **Patch can be applied cleanly** (detail)

**Comment by ageekhere** [comment]
Yeah it does work now
